### ISSUE TITLE
Pass guild id to wumpus vote link

### ISSUE THREAD

**Issue by ZakChrom** [milena-kos/cat-bot#45]
Perhaps pass the guild id to the wumpus.store vote link when doing /vote:
`https://wumpus.store/bot/966695034340663367/vote?guild_id=HERE`
This would allow you to get the guild id directly when a vote comes and not have the vote channel thing in the user db i think
Although you would need to directly link to the vote page instead of the bot page 

The update that added this feature: https://discord.com/channels/1173314351348842627/1183777576989233243/1204525533183086602

**Comment by milena-kos** [comment]
guild id is not much useful
im thinking of maybe tricking it and setting that parameter to channel id but will need testing

**Comment by milena-kos** [comment]
it was just updated to add support for all browser params so we wont even have to hack it
