### ISSUE TITLE
the status is a dead giveaway of the spawn times

### ISSUE THREAD

**Issue by NathanCrazy** [milena-kos/cat-bot#62]
![Screenshot_20240530-072743](https://github.com/milena-kos/cat-bot/assets/97754720/a486d5a9-3e14-4a4b-bfe9-f66ba2c578a3)
we may want to not have the status just update at the beginning of spawning loop 💀 
these times match perfectly with cat stand btw

**Comment by milena-kos** [comment]
stalker behaviour

**Comment by NathanCrazy** [comment]
yep basically

**Comment by NathanCrazy** [comment]
can you not fix it for a bit so I can get some really good catch times though
