### ISSUE TITLE
15 and 16 superposition ‽‽‽

### ISSUE THREAD

**Issue by NathanCrazy** [milena-kos/cat-bot#64]
![Screenshot_20240531-115253](https://github.com/milena-kos/cat-bot/assets/97754720/1e05e02f-c94d-4f3e-bca5-4d87a01277a6)
yeah this is wrong
looked at code and leaderboard seems horrible to try to change
wouldn't even fault you for not fixing it

**Comment by milena-kos** [comment]
this is intended behavior to prevent the other case (user not visible at all if they are tie-pushed to 16)
i suppose i can add a check to ensure they arent already listed as 15
