### ISSUE TITLE
why will channels suddenly stop spawning cats

### ISSUE THREAD

**Issue by NathanCrazy** [milena-kos/cat-bot#73]

**Comment by milena-kos** [comment]
duplicate of #71

**Comment by NathanCrazy** [comment]
nuh uh see slow catching channel at 8:08
this is actually more common than #71

**Comment by NathanCrazy** [comment]
uh 8:08 EDT ig its 15:08 for you?

**Comment by milena-kos** [comment]
in that case closing for insufficient explanation

**Comment by NathanCrazy** [comment]
ok will make new one
