### ISSUE TITLE
misinformation

### ISSUE THREAD

**Issue by dtplsongithub** [milena-kos/cat-bot#75]
uhm actually cats don't always land on their feet
if they fall too fast they know they will break their legs so they land on their stomach 🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓
please stop spreading misinformation 🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓

**Comment by milena-kos** [comment]
@NotRealAz what do you have to say to this

**Comment by NotRealAz** [comment]
shit uhhh uhhhhh 😰 they are lying 😡

**Comment by VishramKidPG123** [comment]
...

**Comment by NotRealAz** [comment]
> uhm actually cats don't always land on their feet if they fall too fast they know they will break their legs so they land on their stomach 🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓 please stop spreading misinformation 🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓

well yes but it was never implied that they always land on their feet
[cats land on their feet]

**Comment by NotRealAz** [comment]
close issue

**Comment by tema5002** [comment]
Привет, я Айгуль и я жива. Мою смерть построили, чтобы Марат помогал следствию раскрыть группировку. Сейчас я в другом городе и мне срочно нужно вернутся, чтобы встретиться с Маратом и рассказать ему правду. Ты можешь мне помочь! Переведи 200 рублей на билет на поезд

**Comment by NotRealAz** [comment]
huh???

**Comment by NotRealAz** [comment]
please close issue. @milena-kos
