### ISSUE TITLE
cat when sus cat appear get sussy cat cat is sus now please help

### ISSUE THREAD

**Issue by RegonGaming** [milena-kos/cat-bot#87]
Cat App get sussy when cat sus appears
Cat App unintended behaviour of sussy cat breaks the law of 
message.author.bot and message.author.id not in WHITELISTED_BOTS
(i think)

![image](https://github.com/user-attachments/assets/3abbffb8-0720-4b3b-b0b4-0e04d0b2426b)

**Comment by milena-kos** [comment]
ok

**Comment by RegonGaming** [comment]
*dies of sus*

**Comment by rech2020** [comment]
> ok

your mother
