### ISSUE TITLE
bring back /warning

### ISSUE THREAD

**Issue by rech2020** [milena-kos/cat-bot#98]
if it continues we're gonna be left with only commands that show some stupid info and gambling (and then milenakos gonna add a shitton p2w things)

**Comment by rech2020** [comment]
look ma im in milenakos mods
![image](https://github.com/user-attachments/assets/8e6684ae-2890-4375-853c-d82736024564)

**Comment by milena-kos** [comment]
it was removed solely and exclusively because it wouldnt make sense to new people who havent seen old cattype images please stop making conspiracy theories up
